#!/bin/bash

function install_libvirt {
    if [ ! -d "$LIBVIRT_SRC_DIR" ]; then
        git clone $LIBVIRT_REPO $LIBVIRT_SRC_DIR
    fi
    
    if [ ! -d "$QEMU_SRC_DIR" ]; then
        git clone $QEMU_REPO $QEMU_SRC_DIR
    fi
}