#!/bin/bash

function install_ovs {

    if _is_ovs_installed; then
        echo "ovs has been installed, so skip it."
        return
    fi
    
    yum -y install autoconf automake libtool
    local dest=$DEST_BASE/src/ovs
    git clone -b branch-2.7 https://github.com/openvswitch/ovs.git $dest
    cd $dest
    ./boot.sh
    ./configure
    make
    make install
    export PATH=$PATH:/usr/local/share/openvswitch/scripts
    ovs-vsctl set-manager ptcp:6640
    ovs-ctl start
}

function _is_ovs_installed {
    if type ovs-ctl >/dev/null 2>&1; then 
        return 0
    else
        return 1
    fi
}

function configure_ovs {
    install -d -o neutron -g neutron $DEST_BASE/etc/neutron/plugins/openvswitch/
    iniset $OVS_AGENT_CONFIG_FILE ovs tunnel_bridge  "br-tun"
    iniset $OVS_AGENT_CONFIG_FILE ovs local_ip  $HOST_IP
    iniset $OVS_AGENT_CONFIG_FILE ovs integration_bridge  "br-int"

    iniset $OVS_AGENT_CONFIG_FILE agent l2_population   "True"
    
    iniset $OVS_AGENT_CONFIG_FILE securitygroup firewall_driver   "neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver"
    iniset $OVS_AGENT_CONFIG_FILE securitygroup enable_security_group   "True"
    
}