#!/bin/bash

function configure_mariadb {
    local cnf="/etc/my.cnf.d/openstack.cnf"
    if [ -f cnf ]; then
        rm -f /etc/my.cnf.d/openstack.cnf
    fi
    
    cat <<EOF | sudo tee cnf
[mysqld]
bind-address = $HOST_IP

default-storage-engine = innodb
innodb_file_per_table = on
max_connections = 4096
collation-server = utf8_general_ci
character-set-server = utf8
EOF

chmod 0600 cnf
}

function do_secure_installation {
    mysqladmin -u root password "$DATABASE_PASSWORD"
    mysql -u root -p"$DATABASE_PASSWORD" -e "UPDATE mysql.user SET Password=PASSWORD('$DATABASE_PASSWORD') WHERE User='root'"
    mysql -u root -p"$DATABASE_PASSWORD" -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
    mysql -u root -p"$DATABASE_PASSWORD" -e "DELETE FROM mysql.user WHERE User=''"
    mysql -u root -p"$DATABASE_PASSWORD" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
    mysql -u root -p"$DATABASE_PASSWORD" -e "FLUSH PRIVILEGES"
}

function configure_keystrone_db {
    mysql -u root -p"$DATABASE_PASSWORD" -e "drop database if exists keystone"
    mysql -u root -p"$DATABASE_PASSWORD" -e "CREATE DATABASE keystone"
    mysql -u root -p"$DATABASE_PASSWORD" -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '$DATABASE_PASSWORD'"
    mysql -u root -p"$DATABASE_PASSWORD" -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '$DATABASE_PASSWORD'"
}

function configure_nova_db {
    mysql -u root -p"$DATABASE_PASSWORD" -e "drop database if exists nova_api"
    mysql -u root -p"$DATABASE_PASSWORD" -e "CREATE DATABASE nova_api"
    mysql -u root -p"$DATABASE_PASSWORD" -e "drop database if exists nova"
    mysql -u root -p"$DATABASE_PASSWORD" -e "CREATE DATABASE nova"
    mysql -u root -p"$DATABASE_PASSWORD" -e "drop database if exists nova_cell0"
    mysql -u root -p"$DATABASE_PASSWORD" -e "CREATE DATABASE nova_cell0"
    mysql -u root -p"$DATABASE_PASSWORD" -e "GRANT ALL PRIVILEGES ON nova_api.* TO 'nova'@'localhost' IDENTIFIED BY '$DATABASE_PASSWORD'"
    mysql -u root -p"$DATABASE_PASSWORD" -e "GRANT ALL PRIVILEGES ON nova_api.* TO 'nova'@'%' IDENTIFIED BY '$DATABASE_PASSWORD'"
    mysql -u root -p"$DATABASE_PASSWORD" -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost' IDENTIFIED BY '$DATABASE_PASSWORD'"
    mysql -u root -p"$DATABASE_PASSWORD" -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%' IDENTIFIED BY '$DATABASE_PASSWORD'"
    mysql -u root -p"$DATABASE_PASSWORD" -e "GRANT ALL PRIVILEGES ON nova_cell0.* TO 'nova'@'localhost' IDENTIFIED BY '$DATABASE_PASSWORD'"
    mysql -u root -p"$DATABASE_PASSWORD" -e "GRANT ALL PRIVILEGES ON nova_cell0.* TO 'nova'@'%' IDENTIFIED BY '$DATABASE_PASSWORD'"
}

function configure_neutron_db {
    mysql -u root -p"$DATABASE_PASSWORD" -e "drop database if exists neutron"
    mysql -u root -p"$DATABASE_PASSWORD" -e "CREATE DATABASE neutron"
    mysql -u root -p"$DATABASE_PASSWORD" -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '$DATABASE_PASSWORD'"
    mysql -u root -p"$DATABASE_PASSWORD" -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '$DATABASE_PASSWORD'"
}

