#!/bin/bash

function add_nova_api_systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/openstack-nova-api.service
[Unit]
Description=OpenStack Nova API Server
After=syslog.target network.target

[Service]
Environment="PYTHONPATH=$DEST_BASE/lib/python2.7/site-packages"
Type=notify
NotifyAccess=all
TimeoutStartSec=0
Restart=always
User=nova
ExecStart=$BIN_DIR/nova-api --config-dir $NOVA_CONF_DIR --config-file $NOVA_CONF

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
}

function add_nova_conductor_systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/openstack-nova-conductor.service

[Unit]
Description=OpenStack Nova Conductor Server
After=syslog.target network.target

[Service]
Environment="PYTHONPATH=$DEST_BASE/lib/python2.7/site-packages"
Type=notify
NotifyAccess=all
TimeoutStartSec=0
Restart=always
User=nova
ExecStart=$BIN_DIR/nova-conductor --config-dir $NOVA_CONF_DIR --config-file $NOVA_CONF

[Install]
WantedBy=multi-user.target

EOF
    systemctl daemon-reload
}


function add_nova_metadata_api_systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/openstack-nova-metadata-api.service

[Unit]
Description=OpenStack Nova Metadata API Server
After=syslog.target network.target

[Service]
Environment="PYTHONPATH=$DEST_BASE/lib/python2.7/site-packages"
Type=notify
NotifyAccess=all
TimeoutStartSec=0
Restart=always
User=nova
ExecStart=$BIN_DIR/nova-api-metadata --config-dir $NOVA_CONF_DIR --config-file $NOVA_CONF

[Install]
WantedBy=multi-user.target


EOF
    systemctl daemon-reload
}

function add_nova_scheduler_systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/openstack-nova-scheduler.service
[Unit]
Description=OpenStack Nova Scheduler Server
After=syslog.target network.target

[Service]
Environment="PYTHONPATH=$DEST_BASE/lib/python2.7/site-packages"
Type=notify
NotifyAccess=all
TimeoutStartSec=0
Restart=always
User=nova
ExecStart=$BIN_DIR/nova-scheduler  --config-dir $NOVA_CONF_DIR --config-file $NOVA_CONF

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
}

function add_nova_compute_systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/openstack-nova-compute.service
[Unit]
Description=OpenStack Nova Compute Server
After=syslog.target network.target libvirtd.service

[Service]
Environment="LIBGUESTFS_ATTACH_METHOD=appliance" PYTHONPATH=$DEST_BASE/lib/python2.7/site-packages
Type=notify
NotifyAccess=all
TimeoutStartSec=0
Restart=always
User=nova
ExecStart=$BIN_DIR/nova-compute --config-dir $NOVA_CONF_DIR --config-file $NOVA_CPU_CONF

[Install]
WantedBy=multi-user.target

EOF
    systemctl daemon-reload
}

function add_nova_consoleauth_systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/openstack-nova-consoleauth.service
[Unit]
Description=OpenStack Nova VNC console auth Server
After=syslog.target network.target

[Service]
Environment="PYTHONPATH=$DEST_BASE/lib/python2.7/site-packages"
Type=notify
NotifyAccess=all
TimeoutStartSec=0
Restart=always
User=nova
ExecStart=$BIN_DIR/nova-consoleauth --config-dir $NOVA_CONF_DIR --config-file $NOVA_CONF

[Install]
WantedBy=multi-user.target

EOF
    systemctl daemon-reload
}


function add-neutron-dhcp-agent-systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/neutron-dhcp-agent.service
[Unit]
Description=OpenStack Neutron DHCP Agent
After=syslog.target network.target

[Service]
Environment="PYTHONPATH=$DEST_BASE/lib/python2.7/site-packages"
Type=simple
User=neutron
ExecStart=$BIN_DIR/neutron-dhcp-agent --config-file $NEUTRON_CONF_DIR/neutron.conf --config-file $NEUTRON_CONF_DIR/dhcp_agent.ini --config-dir $NEUTRON_CONF_DIR --config-dir $NEUTRON_CONF_DIR/conf.d/neutron-dhcp-agent --log-file /var/log/neutron/dhcp-agent.log
PrivateTmp=false
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target

EOF
    systemctl daemon-reload
}


function add-neutron-linuxbridge-agent-systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/neutron-linuxbridge-agent.service
[Unit]
Description=OpenStack Neutron Linux Bridge Agent
After=syslog.target network.target

[Service]
Environment="PYTHONPATH=$DEST_BASE/lib/python2.7/site-packages"
Type=simple
User=neutron
PermissionsStartOnly=true
ExecStartPre=$BIN_DIR/neutron-enable-bridge-firewall.sh
ExecStart=$BIN_DIR//neutron-linuxbridge-agent --config-file $NEUTRON_CONF_DIR/neutron.conf --config-file $NEUTRON_CONF_DIR/plugins/ml2/linuxbridge_agent.ini --config-dir $NEUTRON_CONF_DIR/conf.d/common --config-dir $NEUTRON_CONF_DIR/conf.d/neutron-linuxbridge-agent --log-file /var/log/neutron/linuxbridge-agent.log
PrivateTmp=true
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target

EOF
    systemctl daemon-reload
}

function add-neutron-openvswitch-agent-systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/neutron-openvswitch-agent.service
[Unit]
Description=OpenStack Neutron Open vSwitch Agent
After=syslog.target network.target

[Service]
Environment="PYTHONPATH=$DEST_BASE/lib/python2.7/site-packages"
Type=simple
User=neutron
ExecStart=$BIN_DIR/neutron-openvswitch-agent --config-file $NEUTRON_CONF_DIR/neutron.conf --config-file $NEUTRON_CONF_DIR/plugins/openvswitch/ovs_neutron_plugin.ini --log-file /var/log/neutron/openvswitch-agent.log
PrivateTmp=true

[Install]
WantedBy=multi-user.target

EOF
    systemctl daemon-reload
}

function add-neutron-metadata-agent-systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/neutron-metadata-agent.service
[Unit]
Description=OpenStack Neutron Metadata Agent
After=syslog.target network.target

[Service]
Environment="PYTHONPATH=$DEST_BASE/lib/python2.7/site-packages"
Type=simple
User=neutron
ExecStart=$BIN_DIR/neutron-metadata-agent --config-file $NEUTRON_CONF_DIR/neutron.conf --config-file $NEUTRON_CONF_DIR/metadata_agent.ini --config-dir $NEUTRON_CONF_DIR/conf.d/common --config-dir $NEUTRON_CONF_DIR/conf.d/neutron-metadata-agent --log-file /var/log/neutron/metadata-agent.log
PrivateTmp=false
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
}

function add-neutron-l3-agent-systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/neutron-l3-agent.service
[Unit]
Description=OpenStack Neutron Layer 3 Agent
After=syslog.target network.target

[Service]
Environment="PYTHONPATH=$DEST_BASE/lib/python2.7/site-packages"
Type=simple
User=neutron
ExecStart=$BIN_DIR/neutron-l3-agent --config-file $NEUTRON_CONF_DIR/l3_agent.ini --config-file $NEUTRON_CONF_DIR/neutron.conf --config-dir $NEUTRON_CONF_DIR/conf.d/common --config-dir $NEUTRON_CONF_DIR/conf.d/neutron-l3-agent --log-file /var/log/neutron/l3-agent.log
PrivateTmp=false
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target

EOF
    systemctl daemon-reload
}

function add_neutron_server_systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/neutron-server.service
[Unit]
Description=OpenStack Neutron Server
After=syslog.target network.target

[Service]
Environment="PYTHONPATH=$DEST_BASE/lib/python2.7/site-packages"
Type=notify
User=neutron
ExecStart=$BIN_DIR/neutron-server --config-dir $NEUTRON_CONF_DIR/server --config-file $NEUTRON_CONF_DIR/neutron.conf --config-dir $NEUTRON_CONF_DIR/conf.d/common --config-dir $NEUTRON_CONF_DIR/conf.d/neutron-server  --config-file /openstack/etc/neutron/plugins/ml2/ml2_conf.ini --log-file /var/log/neutron/server.log
PrivateTmp=true
NotifyAccess=all
KillMode=process
Restart=on-failure
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target

EOF
    systemctl daemon-reload
}

function add_neutron_linuxbridge_cleanup_systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/neutron-linuxbridge-cleanup.service
[Unit]
Description=OpenStack Neutron Linux Bridge Cleanup Utility
After=syslog.target network.target
Before=neutron-linuxbridge-agent.service neutron-dhcp-agent.service neutron-l3-agent.service openstack-nova-compute.service

[Service]
Type=oneshot
User=neutron
ExecStart=$BIN_DIR/neutron-linuxbridge-cleanup --config-file $NEUTRON_CONF_DIR/neutron.conf --config-file $NEUTRON_CONF_DIR/plugins/ml2/linuxbridge_agent.ini --config-dir $NEUTRON_CONF_DIR/conf.d/common --config-dir $NEUTRON_CONF_DIR/conf.d/neutron-linuxbridge-cleanup --log-file /var/log/neutron/linuxbridge-cleanup.log
ExecStop=$BIN_DIR/neutron-linuxbridge-cleanup --config-file $NEUTRON_CONF_DIR/neutron.conf --config-file $NEUTRON_CONF_DIR/plugins/ml2/linuxbridge_agent.ini --config-dir $NEUTRON_CONF_DIR/conf.d/common --config-dir $NEUTRON_CONF_DIR/conf.d/neutron-linuxbridge-cleanup --log-file /var/log/neutron/linuxbridge-cleanup.log
PrivateTmp=true
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target


EOF
    systemctl daemon-reload
}

function add_neutron_netns_cleanup_systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/neutron-netns-cleanup.service
[Unit]
Description=OpenStack Neutron Netns Cleanup Utility
After=syslog.target network.target openvswitch.service
Before=neutron-openvswitch-agent.service neutron-dhcp-agent.service neutron-l3-agent.service openstack-nova-compute.service

[Service]
Type=oneshot
User=neutron
ExecStart=$BIN_DIR/neutron-netns-cleanup --config-file $NEUTRON_CONF_DIR/neutron.conf --config-file $NEUTRON_CONF_DIR/dhcp_agent.ini --config-dir $NEUTRON_CONF_DIR/conf.d/common --config-dir $NEUTRON_CONF_DIR/conf.d/neutron-netns-cleanup --log-file /var/log/neutron/netns-cleanup.log
ExecStop=$BIN_DIR/neutron-netns-cleanup --config-file $NEUTRON_CONF_DIR/neutron.conf --config-file $NEUTRON_CONF_DIR/dhcp_agent.ini --config-dir $NEUTRON_CONF_DIR/conf.d/common --config-dir $NEUTRON_CONF_DIR/conf.d/neutron-netns-cleanup --log-file /var/log/neutron/netns-cleanup.log --force
PrivateTmp=false
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target


EOF
    systemctl daemon-reload
}


function add_neutron_ovs_cleanup_systemctl {
    cat <<EOF | sudo tee /etc/systemd/system/neutron-ovs-cleanup.service
[Unit]
Description=OpenStack Neutron Open vSwitch Cleanup Utility
After=syslog.target network.target openvswitch.service
Before=neutron-openvswitch-agent.service neutron-dhcp-agent.service neutron-l3-agent.service openstack-nova-compute.service

[Service]
Type=oneshot
User=neutron
ExecStart=$BIN_DIR/neutron-ovs-cleanup --config-file $NEUTRON_CONF_DIR/neutron.conf --config-file $NEUTRON_CONF_DIR/plugins/ml2/openvswitch_agent.ini --config-dir $NEUTRON_CONF_DIR/conf.d/common --config-dir $NEUTRON_CONF_DIR/conf.d/neutron-ovs-cleanup --log-file /var/log/neutron/ovs-cleanup.log
ExecStop=$BIN_DIR/neutron-ovs-cleanup --config-file $NEUTRON_CONF_DIR/neutron.conf --config-file $NEUTRON_CONF_DIR/plugins/ml2/openvswitch_agent.ini --config-dir $NEUTRON_CONF_DIR/conf.d/common --config-dir $NEUTRON_CONF_DIR/conf.d/neutron-ovs-cleanup --log-file /var/log/neutron/ovs-cleanup.log
PrivateTmp=true
RemainAfterExit=yes
TimeoutSec=0

[Install]
WantedBy=multi-user.target

EOF
    systemctl daemon-reload
}












